language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jonhong/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonhong/multi-docker npm test -- --coverage

after_success:
  - docker build -t jonhong/multi-client ./client
  - docker build -t jonhong/multi-nginx ./nginx
  - docker build -t jonhong/multi-server ./server
  - docker build -t jonhong/multi-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take images and push to docker
  - docker push jonhong/multi-client
  - docker push jonhong/multi-nginx
  - docker push jonhong/multi-server
  - docker push jonhong/multi-worker
